export { default as any } from './intent.any'
export { default as conversor } from './intent.conversor'
export { default as movie } from './intent.movie'
export { default as translate } from './intent.translate'
export { default as weather } from './intent.weather'
